
name: Lint Reusable

on:
  workflow_call:
    inputs:
      modules:
        required: true
        type: string
      go-version:
        required: true
        type: string
      golangci-lint-version:
        required: true
        type: string

jobs:
  golangci-lint:
    name: Lint all Go modules
    runs-on: ubuntu-latest

    steps:
      - name: ðŸ“¦ Checkout code
        uses: actions/checkout@v4.2.2

      - name: ðŸ›  Set up Go
        uses: actions/setup-go@v5.4.0
        with:
          go-version: ${{ inputs.go-version }}

      - name: ðŸ¾ Show go.work (debug)
        run: cat go.work || echo "â— go.work not found"

      - name: ðŸ“Œ Install Task
        uses: arduino/setup-task@v2.0.0

      - name: ðŸ›  Install mockery
        env:
          BIN_DIR: ./bin
          MOCKERY: ./bin/mockery
          MOCKERY_VERSION: v2.16.0
        run: |
          mkdir -p $BIN_DIR
          ABS_BIN=$(realpath $BIN_DIR)
          if [ ! -f $MOCKERY ]; then
          echo "ðŸ“¦ Installing mockery..."
          GOBIN=$ABS_BIN go install github.com/vektra/mockery/v2@$MOCKERY_VERSION
          fi
          chmod +x $MOCKERY

      - name: ðŸ”§ Add ./bin to PATH
        run: echo "${{ github.workspace }}/bin" >> $GITHUB_PATH
      

      - name: âœ… Run golangci-lint via Taskfile
        env:
          MODULES: ${{ inputs.modules }}
          GOLANGCI_LINT_VERSION: ${{ inputs.golangci-lint-version }}
        run: task lint
